version: '3.7'
services:
  boringproxy:
    container_name: boringproxy-server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - storage:/storage/
      - ssh://.ssh
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
    command: ["server", "-admin-domain", "bp.example.com", "-acme-email", "your-email-address", "-accept-ca-terms", "-cert-dir", "/storage/certmagic", "-print-login"]
    environment:
      USER: "root"

volumes:
  storage:
  ssh: