version: '3.7'

services:
  boringproxy:
    image: ghcr.io/wgrobler/boringproxy-linux-amd64:latest
    restart: unless-stopped
    command: ["client", "-server", "bp.example.com", "-token", "your-user-token", "-acme-email", "your-email-address", "-cert-dir", "/certmagic"]
    volumes:
      - certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro

  nginx:
    image: nginx:1.17
    hostname: nginx
    ports:
      - 8080:80 # Enable port on local machine, can be removed if you only want to use the tunnel

volumes:
  certmagic: