version: '3.7'
services:
  boringproxy:
    container_name: boringproxy-client
    restart: unless-stopped
    command: ["client", "-server", "bp.example.com", "-token", "your-user-token", "-acme-email", "your-email-address", "-cert-dir", "/certmagic"]
    volumes:
      - certmagic:/certmagic
      - /etc/ssl/certs/:/etc/ssl/certs/:ro

volumes:
  certmagic: